### ISSUE TITLE
STMonadTrans-0.3.4 test suite failure

### ISSUE THREAD

**Issue by peti** [josefs/STMonadTrans#4] opened 2016-11-06 19:31 UTC
Citing from http://hydra.cryp.to/build/2050179/nixlog/2/raw:

~~~
Running 1 test suites...
Test suite foo: RUNNING...
Prelude.read: no parse
~~~~

**Comment by josefs** [comment] 2016-11-07 13:30
How can I go about replicating this? Given that you're using nix, is there a nix expression you could send me that I can run to tickle this bug, @peti ?

I expect this is a bug in Cabal because I'm not using Prelude.read anywhere. That said, I'm new to the test-suite functionality of Cabal so I might have gotten something wrong.

**Comment by peti** [comment] 2016-11-08 14:53
Run

```
nix-build "<nixpkgs>" -A haskellPackages.STMonadTrans
```

to re-produce the build with Nix. This assumes that the default Nixpkgs branch is `master` or `unstable`. The same issue _might_ exist in the `release-16.09` branch but I haven't actually tested that.

**Comment by bennofs** [comment] 2017-01-27 11:03
Submitted as a cabal bug in haskell/cabal#4270

**Comment by josefs** [comment] 2017-01-30 20:12
Thanks for looking into this issue @bennofs .

**Comment by andreasabel** [comment] 2020-12-28 11:02
> Submitted as a cabal bug in [haskell/cabal#4270](https://github.com/haskell/cabal/issues/4270)

Following the recipe there, I cannot reproduce the failure any longer.
Closing, thanks to upstream for the fixes.

**Closed as completed by andreasabel** 2020-12-28 11:02 UTC
